import "./globals.css";
export const metadata = {
  title: "Home",
  desciotion: "Generated by Create Naext App",
};

export default function Home() {
  return (
    <>
      <div className="mt-[200px] ">
        <p className=" text-center upprtcase text-xl text-slate-500">
          Please sign a rental contract to access information.
        </p>{" "}
      </div>
    </>
  );
}
